# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tAz7XUM20JH3sbwgiRvuaj0j5VjB_ie8
"""

import numpy as np
import matplotlib.pylab as plt

sfreq = 10000 #サンプリング周波数(青点)
sfreq2 = 100000 #サンプリング周波数2(連続関数は表現できないためその代わりとして使う)
slen = 100000 #データ総数(slen/sfreq を計算すると何秒間のデータかがわかる)
f = 2000 #振動数(今回は１秒間に2000回振動する波を作っている)
A = np.sqrt(2)

t = np.arange(slen) / sfreq #0s～10sまで0.0001s間隔で区切ったndarray(多次元配列), slen個のデータが入る多次元配列
s = A * np.sin(2 * np.pi * f * t) #サンプリング(青点)の波の式 2πftの部分は(2π:1周あたりの角度,f:1秒間に何回転させたいか,t:経過時間)A:実行値を1.0にしたいなら波の振幅をroot2倍する必要がある
t2 = np.arange(slen) / sfreq2 #0s～1sまで0.00001s間隔で区切った多次元配列
s2 = A * np.sin(2 * np.pi * f * t2) #連続関数とみなす波の式
plt.plot(t * 1e3, s, 'o', label='Samples (sfreq = 10 kHz)') # t*1e3:x軸データ1000倍して単位をsからmsに変更している s:y軸データsの値が入っている 'o':フォーマット文字列今回は点を表示 label:ラベル
plt.plot(t2 * 1e3, s2, '--', label='Samples (sfreq = 100 kHz)') # '--':破線を表示
plt.legend(loc='upper right') #判例を表示するためのコード↑で指定したlabelの内容を出力locで位置を決めている
plt.xlim([0,2]) #x軸の表示範囲を制限するコード
plt.ylabel('Amplitude') #ラベルを表示
plt.xlabel('Time (ms)') #ラベルを表示
plt.show() #グラフ表示

intensity = s ** 2 #瞬時電力(信号の強さの二乗)
energy = (intensity * 1 / sfreq).sum() #全エネルギー(瞬時電力をtで積分、それを近似的に表している) 1/sfreq=dt,intensity*dtをsum
power = (energy) / (slen / sfreq) #平均電力(全エネルギーを時間で割っている)
power_theory = A ** 2 / 2 #理論的な平均電力(sinの平均電力は振幅の二乗/2となることが数学的に証明されている)
energy_theory = power_theory * slen / sfreq #理論的な全エネルギー(平均電力*時間)
ave_intensity = intensity.mean() #強度の時間平均
print('Energy: {}'.format(energy))
print('Power: {}'.format(power))
print('Energy (theory): {}'.format(energy_theory))
print('Power (theory): {}'.format(power_theory))
print('Average intensity: {}'.format(ave_intensity))

sf = np.fft.fft(s,norm = 'forward') #sをフーリエ変換した
ffreq = np.fft.fftfreq(slen, 1 / sfreq) #フーリエ変換したsの周波数軸
plt.plot(ffreq * 1e-3, np.abs(sf), label='Spectrum (sfreq = 10 kHz)')
plt.xlim([-3,3])
plt.xlabel('Frequency (kHz)')
plt.ylabel('Amplitude')
plt.legend()
plt.show()

fourier_average_intensity = np.mean(np.abs(sf)**2) * slen
print(f'Average intensity in frequency field: {fourier_average_intensity}')
# 時間領域のaverage_intensityと一致！！

sample_freq = np.ndarray.tolist(np.arange(1000, 10001, 500)) #サンプル周波数の配列

# print(sample_freq)

sample_t = [] #サンプル周波数ごとのtのndarray
for i in range(len(sample_freq)):
    sample_t.append(np.arange(slen) / sample_freq[i])

# print(sample_t)

sample_cos = [] #サンプルごとの余弦波データ配列
for i in range(len(sample_freq)):
  sample_cos.append(np.cos(2 * np.pi * f * sample_t[i]))

f_sample_cos = np.fft.fft(sample_cos) #フーリエ変換したサンプルごとの余弦波データ配列

f_sample_freq = [] #サンプルごとのsの周波数軸
for i in range(len(sample_freq)):
  f_sample_freq.append(np.fft.fftfreq(slen, 1 / sample_freq[i]))

# for i in range(len(sample_freq)):
#   plt.plot(f_sample_freq[i],np.abs(f_sample_cos[i]) * 1e-4,label='Spectrum (sfreq = {} kHz)')
#   plt.xlabel('Frequency (kHz)')
#   plt.ylabel('Amplitude')
#   plt.show()

peak = []
for i in range(len(sample_freq)):
  amplitude = np.abs(f_sample_cos[i])
  max_idx = np.argmax(amplitude)
  peak_freq_value = np.abs(f_sample_freq[i][max_idx])
  peak.append(peak_freq_value)

plt.plot(np.array(sample_freq) * 1e-3, np.array(peak) * 1e-3, 'o')
plt.plot(np.array(sample_freq) * 1e-3, np.array(peak) * 1e-3)
plt.xlabel('Sample frequency (kHz)')
plt.ylabel('Peak frequency (kHz)')
plt.show()

# グラフよりサンプル周波数が4kHz以上ならok

# 3.2

# --- パラメータの設定 ---
# 1. 時間軸のパラメータ
fs = 10000       # サンプリング周波数 [Hz]
N = 100000       # サンプル数
dt = 1 / fs      # サンプリング間隔 [s]
t_start = -5.0   # 開始時間 [s]

# 時間配列 t を生成 [-5.0s, -4.9999s, ..., +4.9999s]
t = np.arange(N) * dt + t_start

# 2. 矩形信号 r(t) のパラメータ (式(1)に基づく)
tau = 0.1        # 時間幅 100 ms = 0.1 s
T0 = 0.0         # 中心時間

# --- 矩形信号データの生成 ---
# 定義式 r(t - T0) の |t - T0| <= tau / 2 の条件をNumPyの比較演算で実装
# True を 1.0 に、False を 0.0 に変換
rect_signal = (np.abs(t - T0) <= tau / 2).astype(float)

# --- グラフの描画 ---
plt.figure(figsize=(10, 8))

# グラフ2: 中心付近を拡大した様子 (パルス幅がわかるように)
plt.subplot(2, 1, 2) # 2行1列の2番目
# パルス幅を中心に、±0.2秒の範囲を拡大表示
plt.plot(t, rect_signal)
plt.title('r(t)(τ=100.0ms)')
plt.xlabel('Time [s]')
plt.ylabel('Amplitude')
plt.grid(True)
plt.xlim(T0 - 0.2, T0 + 0.2) # 中心±0.2秒の範囲
plt.ylim(-0.1, 1.1)

# 全体のレイアウトを調整
plt.tight_layout()
plt.show()

R_fft_raw = np.fft.fft(rect_signal)

# 連続時間フーリエ変換の解析解と合わせるためのスケーリング（重要！）
R_fft = R_fft_raw * dt

# 周波数軸を [0, fs] から [-fs/2, fs/2] に並べ替える
R_fft_shifted = np.fft.fftshift(R_fft)
freqs = np.fft.fftfreq(N, d=dt)
freqs_shifted = np.fft.fftshift(freqs)

# --- 5. グラフの描画 ---
plt.figure(figsize=(10, 5))

# 振幅絶対値スペクトルの比較
plt.plot(freqs_shifted, np.abs(R_fft_shifted), label='Numerical (FFT)', alpha=0.8)

# 見やすくするための表示範囲設定
plt.xlim(-100, 100) # メインローブ付近を拡大
plt.ylim(0, 0.11)
plt.xlabel('Frequency [Hz]')
plt.ylabel('Magnitude $|R(f)|$')
plt.title('Comparison of FFT and Analytical Solution')
plt.legend()
plt.grid(True)
plt.show()

# --- 4. 解析解 R(f) = tau * sinc(tau * f) の計算 ---
# np.sinc(x) は sin(pi*x)/(pi*x) なので、引数はそのまま (tau * f) でOK
R_analytical = tau * np.sinc(tau * freqs_shifted)

# --- 5. グラフの描画 ---
plt.figure(figsize=(10, 5))

# 振幅絶対値スペクトルの比較
plt.plot(freqs_shifted, np.abs(R_fft_shifted), label='Numerical (FFT)', alpha=0.8)
plt.plot(freqs_shifted, np.abs(R_analytical), label='Analytical (sinc)', linestyle='--', color='red')

# 見やすくするための表示範囲設定
plt.xlim(-100, 100) # メインローブ付近を拡大
plt.ylim(0, 0.11)
plt.xlabel('Frequency [Hz]')
plt.ylabel('Magnitude $|R(f)|$')
plt.title('Comparison of FFT and Analytical Solution')
plt.legend()
plt.grid(True)
plt.show()

# フィルタのパラメータ
W = 100.0 # 0.1kHz

# H(f)の定義
H = np.where(np.abs(freqs_shifted)<= W/2, 1.0 + 0.0j, 0.0 + 0.0j)

G_fft_shifted = R_fft_shifted * H

# --- グラフ描画 --- (制限したスペクトル波形)
# 左側：フィルタ後のスペクトル
plt.plot(freqs_shifted, np.abs(G_fft_shifted))
plt.title(f'Filtered Spectrum (W = {W} Hz)')
plt.xlim(-150, 150) # 比較しやすいように範囲を固定
plt.grid(True)
plt.xlabel('Frequency [Hz]')
plt.ylabel('Magnitude $|R(f)|$')

# フーリエ逆変換の実行
# 3. 逆フーリエ変換 (IFFT)
# シフトを戻してからIFFTを行い、スケーリング(dt)を逆算
g_t = np.fft.ifft(np.fft.ifftshift(G_fft_shifted)) / dt
# 実部のみ抽出
g_t_real = np.real(g_t)

# --- グラフ描画 --- (フィルタ抽出時間波形)
plt.plot(t, rect_signal, 'k--', alpha=0.3, label='Original')
plt.plot(t, g_t_real, label=f'Filtered (W={W}Hz)')
plt.title(f'Output Time Waveform (W = {W} Hz)')
plt.xlim(-0.15, 0.15) # パルス付近を拡大
plt.ylim(-0.2, 1.3)
plt.legend()
plt.grid(True)
plt.xlabel('Time [s]')
plt.ylabel('Amplitude')

# フィルタのパラメータ より狭くしたバージョン
W = 20.0 # 0.02kHz

# H(f)の定義
H = np.where(np.abs(freqs_shifted)<= W/2, 1.0 + 0.0j, 0.0 + 0.0j)

G_fft_shifted = R_fft_shifted * H

# --- グラフ描画 --- (制限したスペクトル波形)
# 左側：フィルタ後のスペクトル
plt.plot(freqs_shifted, np.abs(G_fft_shifted))
plt.title(f'Filtered Spectrum (W = {W} Hz)')
plt.xlim(-150, 150) # 比較しやすいように範囲を固定
plt.grid(True)
plt.xlabel('Frequency [Hz]')
plt.ylabel('Magnitude $|R(f)|$')

# フーリエ逆変換の実行
# 3. 逆フーリエ変換 (IFFT)
# シフトを戻してからIFFTを行い、スケーリング(dt)を逆算
g_t = np.fft.ifft(np.fft.ifftshift(G_fft_shifted)) / dt
# 実部のみ抽出
g_t_real = np.real(g_t)

# --- グラフ描画 --- (フィルタ抽出時間波形)
plt.plot(t, rect_signal, 'k--', alpha=0.3, label='Original')
plt.plot(t, g_t_real, label=f'Filtered (W={W}Hz)')
plt.title(f'Output Time Waveform (W = {W} Hz)')
plt.xlim(-0.15, 0.15) # パルス付近を拡大
plt.ylim(-0.2, 1.3)
plt.legend()
plt.grid(True)
plt.xlabel('Time [s]')
plt.ylabel('Amplitude')

# フィルタのパラメータ 広くしたバージョン
W = 500.0 # 0.5kHz

# H(f)の定義
H = np.where(np.abs(freqs_shifted)<= W/2, 1.0 + 0.0j, 0.0 + 0.0j)

G_fft_shifted = R_fft_shifted * H

# --- グラフ描画 --- (制限したスペクトル波形)
# 左側：フィルタ後のスペクトル
plt.plot(freqs_shifted, np.abs(G_fft_shifted))
plt.title(f'Filtered Spectrum (W = {W} Hz)')
plt.xlim(-150, 150) # 比較しやすいように範囲を固定
plt.grid(True)
plt.xlabel('Frequency [Hz]')
plt.ylabel('Magnitude $|R(f)|$')

# フーリエ逆変換の実行
# 3. 逆フーリエ変換 (IFFT)
# シフトを戻してからIFFTを行い、スケーリング(dt)を逆算
g_t = np.fft.ifft(np.fft.ifftshift(G_fft_shifted)) / dt
# 実部のみ抽出
g_t_real = np.real(g_t)

# --- グラフ描画 --- (フィルタ抽出時間波形)
plt.plot(t, rect_signal, 'k--', alpha=0.3, label='Original')
plt.plot(t, g_t_real, label=f'Filtered (W={W}Hz)')
plt.title(f'Output Time Waveform (W = {W} Hz)')
plt.xlim(-0.15, 0.15) # パルス付近を拡大
plt.ylim(-0.2, 1.3)
plt.legend()
plt.grid(True)
plt.xlabel('Time [s]')
plt.ylabel('Amplitude')

#3.3

# ガウス雑音の生成
# --- パラメータ設定 ---
fs = 10000       # サンプリング周波数 10kHz
N = 100000       # サンプル数 10^5
mu = 0.0         # 平均 (loc)
sigma = 1.0      # 標準偏差 (scale) ※分散1なので標準偏差も1
dt = 1/fs

# 1. ガウス雑音の生成
noise = np.random.normal(loc=mu, scale=sigma, size=N)

# 2. パワーと分散の計算
# 平均 0 の場合、パワー（二乗平均）と分散は一致します
power = np.mean(noise**2)
variance = np.abs(np.var(noise))

print(f"平均値: {np.mean(noise):.4f}")
print(f"分散:   {variance:.4f}")
print(f"パワー: {power:.4f}")

# ガウス雑音の時間波形の出力
fig = plt.figure(figsize=(14, 8))

# (A) 時間波形：全体像
ax1 = plt.subplot2grid((2, 3), (0, 0), colspan=2)
ax1.plot(t, noise, lw=0.5)
ax1.set_title('Gaussian Noise Time Waveform (Whole)')
ax1.set_xlabel('Time [s]')
ax1.set_ylabel('Amplitude')
ax1.grid(True)
plt.show()

# (B) 時間波形：一部拡大 (0秒付近の10ms分を表示)
ax2 = plt.subplot2grid((2, 3), (1, 0), colspan=2)

# 時間をミリ秒(ms)に変換
t_ms = t * 1000

# プロットのスタイルを変更
# 'o--' は 点(marker='o') と 点線(linestyle='--') を組み合わせたスタイル
# markersize で点の大きさを調整
ax2.plot(t_ms, noise, 'o--', markersize=4, lw=1, label='Samples')

# x軸の範囲を 0ms から 10ms に設定
ax2.set_xlim(0, 5)

ax2.set_title('Gaussian Noise Time Waveform (Zoomed: 5ms)')
ax2.set_xlabel('Time [ms]') # ラベルを ms に変更
ax2.set_ylabel('Amplitude')
ax2.grid(True)

# 3. ヒストグラムの計算と描画
# density=True にすることで、面積の合計が1になり確率密度関数と比較可能になります
count, bins, ignored = plt.hist(noise, bins=100, density=True,
                                alpha=0.6, color='g', label='Noise Histogram', orientation='horizontal')

# 4. 理論的なガウス分布の確率密度関数 (PDF) の計算
# 問題文の式: p = np.exp(-1 * (x-0)**2 / (2*1)) / np.sqrt(2 * np.pi)
x = np.linspace(-4, 4, 1000)
p = np.exp(-1 * (x - mu)**2 / (2 * sigma**2)) / (np.sqrt(2 * np.pi) * sigma)

# プロット
plt.plot(p, x, color='r', lw=2, label='Theoretical PDF $N(0, 1)$')
plt.title('Gaussian Noise: Histogram vs Theoretical PDF')
plt.xlabel('Value')
plt.ylabel('Probability Density')
plt.legend()
plt.grid(True)
plt.show()

# ガウス雑音をフーリエ変換
R_fft = np.fft.fft(noise)
fft_noise = np.fft.fftshift(R_fft) * dt
freqs_noise = np.fft.fftshift(np.fft.fftfreq(N, d=dt))

# ガウス雑音をフィルター通してフーリエ変換
W = 5000.0  # 5 kHz
H = np.where(np.abs(freqs_noise) <= W / 2, 1.0 + 0.0j, 0.0 + 0.0j)
f_fft_noise = fft_noise * H

# --- 6. グラフ描画 ---
fig = plt.figure(figsize=(12, 10))

# (a) 振幅スペクトルの比較
plt.subplot(2, 1, 1)
plt.plot(freqs_noise, np.abs(fft_noise), label='Input (AWGN)', color='blue')
plt.title(f'Amplitude Spectrum Comparison (W = {W/1000} kHz)')
plt.xlabel('Frequency [Hz]')
plt.ylabel('Magnitude')
plt.legend()
plt.grid(True)

# --- 6. グラフ描画 ---
fig = plt.figure(figsize=(12, 10))

# (a) 振幅スペクトルの比較
plt.subplot(2, 1, 1)
plt.plot(freqs_noise, np.abs(f_fft_noise), label='Output (Filtered)', color='blue')
plt.title(f'Amplitude Spectrum Comparison (W = {W/1000} kHz)')
plt.xlabel('Frequency [Hz]')
plt.ylabel('Magnitude')
plt.legend()
plt.grid(True)

# --- 4. 逆フーリエ変換 (出力雑音の時間波形) ---
noise_out = np.real(np.fft.ifft(np.fft.ifftshift(f_fft_noise))) / dt

t_ms = t * 1000

plt.figure(figsize=(12, 6))

# (1) 入力雑音を背後に薄く描画 (alpha=0.4)
plt.plot(t_ms, noise, color='blue', alpha=0.4, label='Input (AWGN)')

# (2) 出力雑音を重ねて描画
plt.plot(t_ms, noise_out, color='orange', label='Output (Filtered: W=5kHz)')

# --- グラフの体裁 ---
plt.xlim(0, 10)  # 0msから10msの範囲
plt.ylim(-4, 4)
plt.title('Comparison of Input and Output Noise Time Waveforms')
plt.xlabel('Time [ms]')
plt.ylabel('Amplitude')
plt.grid(True, which='both', linestyle=':', alpha=0.5)
plt.legend(loc='upper right')

plt.tight_layout()
plt.show()

# --- 5. 統計量の確認 ---
var_in = np.var(noise)
var_out = np.var(noise_out)
print(f"入力雑音の分散: {var_in:.4f}")
print(f"出力雑音の分散: {var_out:.4f}")
print(f"分散の比率 (出力/入力): {var_out / var_in:.4f} (理論値: 0.5)")

# (b) ヒストグラムの比較
plt.hist(noise, bins=100, density=True, alpha=0.4, color='blue', label=f'Input (var={var_in:.2f})', orientation='horizontal')
plt.hist(noise_out, bins=100, density=True, alpha=0.6, color='orange', label=f'Output (var={var_out:.2f})', orientation='horizontal')
plt.legend()
plt.xlabel('Plobability density')
plt.ylabel('Amplitude')

# --- 1. パラメータ設定 ---
fs = 10000       # 10kHz
N = 100000       # 10^5 samples
dt = 1 / fs
t = np.arange(N) * dt - 5.0  # -5秒から5秒

# 信号の生成
tau = 0.1        # 100ms
rect = (np.abs(t) <= tau / 2).astype(float) # オリジナルの矩形波

# 雑音の生成 (分散1)
noise = np.random.normal(0, 1, N)

# 入力信号 (信号 + 雑音)
signal_in = rect + noise

# --- 2. フィルタ処理 (W = 100Hz = 0.1kHz) ---
W = 100.0
# フーリエ変換
S_in_fft = np.fft.fftshift(np.fft.fft(signal_in)) * dt
freqs = np.fft.fftshift(np.fft.fftfreq(N, d=dt))

# LPF H(f)
H = np.where(np.abs(freqs) <= W / 2, 1.0 + 0.0j, 0.0 + 0.0j)
S_out_fft = S_in_fft * H

# 逆フーリエ変換
signal_out = np.real(np.fft.ifft(np.fft.ifftshift(S_out_fft))) / dt

# --- 3. 時間波形の描画 ---
plt.figure(figsize=(8, 7))

# 背景に入力信号（雑音まみれ）を薄く表示
plt.plot(t, signal_in, color='blue', alpha=0.7, label='Input (Rect + Noise)')

# 元の理想的な矩形波を点線で表示
plt.plot(t, rect, color='lightgreen', lw=1, label='Original Rect')

# フィルタ出力
plt.plot(t, signal_out, color='orange', lw=2, label=f'Filtered Output (W={W}Hz)')

# 拡大表示（パルス前後 200ms 程度）
plt.xlim(-0.2, 0.2)
plt.ylim(-1.5, 2.5)

plt.title('Filter Input and Output Time Waveforms')
plt.xlabel('Time [s]')
plt.ylabel('Amplitude')
plt.grid(True, which='both', alpha=0.3)
plt.legend(loc='upper right')

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# --- 1. パラメータ設定 ---
fs = 10000       # サンプリング周波数 10kHz
N = 100000       # サンプル数 10^5
dt = 1 / fs
t = np.arange(N) * dt - 5.0
tau = 0.1        # 矩形波の時間幅 100ms

# 信号の生成
rect = (np.abs(t) <= tau / 2).astype(float) # オリジナルの矩形波
noise = np.random.normal(0, 1, N)           # 分散1のガウス雑音
signal_in = rect + noise                    # 雑音付加信号

# フーリエ変換
rect_fft = np.fft.fftshift(np.fft.fft(rect)) * dt
freqs = np.fft.fftshift(np.fft.fftfreq(N, d=dt))
S_in_fft = np.fft.fftshift(np.fft.fft(signal_in)) * dt

# --- 2. フィルタ処理と描画 ---
# 比較する帯域幅 W [Hz] のリスト
W_list = [20, 100, 500]
colors = ['orange', 'orange', 'orange']

fig, axes = plt.subplots(len(W_list), 2, figsize=(15, 12), constrained_layout=True)

for i, W in enumerate(W_list):
    # 理想LPF H(f) の適用
    H = np.where(np.abs(freqs) <= W / 2, 1.0 + 0.0j, 0.0 + 0.0j)
    S_out_fft = S_in_fft * H

    # 逆フーリエ変換 (時間領域へ戻す)
    signal_out = np.real(np.fft.ifft(np.fft.ifftshift(S_out_fft))) / dt

    # --- 左側：時間波形のプロット ---
    ax_t = axes[i, 0]
    ax_t.plot(t, signal_in, color='blue', alpha=0.7, label='Input (Rect+Noise)')
    ax_t.plot(t, rect, color='lightgreen', lw=1, label='Original Rect')
    ax_t.plot(t, signal_out, color=colors[i], lw=2, label=f'Filtered (W={W}Hz)')
    ax_t.set_xlim(-0.2, 0.2)
    ax_t.set_ylim(-1.5, 2.0)
    ax_t.set_title(f'Time Waveform (W = {W} Hz)')
    ax_t.set_xlabel('Time [s]')
    ax_t.set_ylabel('Amplitude')
    ax_t.legend(loc='upper right', fontsize='small')
    ax_t.grid(True, alpha=0.3)

    # --- 右側：振幅スペクトルのプロット ---
    ax_f = axes[i, 1]
    ax_f.plot(freqs, np.abs(S_in_fft), color='blue', alpha=0.7, label='Input Spectrum')
    ax_f.plot(freqs, np.abs(S_out_fft), color=colors[i], label='Filtered Spectrum')
    ax_f.plot(freqs, np.abs(rect_fft), color='green', lw=1, label='Original Rect')
    ax_f.set_xlim(-150, 150)
    ax_f.set_ylim(0, 0.12)
    ax_f.set_title(f'Amplitude Spectrum (W = {W} Hz)')
    ax_f.set_xlabel('Frequency [Hz]')
    ax_f.set_ylabel('Magnitude')
    ax_f.legend(loc='upper right', fontsize='small')
    ax_f.grid(True, alpha=0.3)

plt.show()